version: "3"
services:
  payment-service:
    build: payment-service
    container_name: payment-service
    ports:
      - 8060:8060

  inventory-service:
    build: inventory-service
    container_name: inventory-service
    ports:
      - 8070:8070
    depends_on:
      - payment-service

  notification-service:
    build: notification-service
    container_name: notification-service
    ports:
      - 8090:8090
    depends_on:
      - inventory-service

  order-service:
    build: order-service
    container_name: order-service
    ports:
      - 8080:8080
    depends_on:
      - notification-service
